# Generated by Django 5.1.3 on 2025-03-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_product_trainer_alter_payment_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='FullName',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
