# Generated by Django 5.1.3 on 2025-03-07 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_rename_first_name_customuser_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='FullName',
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='Anonymous User', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.product'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.customuser'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.booking'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='expertise',
            field=models.CharField(choices=[('yoga', 'Yoga'), ('strength_training', 'Strength Training'), ('cardio', 'Cardio'), ('nutrition', 'Nutrition'), ('pilates', 'Pilates')], max_length=50),
        ),
    ]
