# Generated by Django 5.1.3 on 2025-03-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_remove_customuser_fullname_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='X',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='facebook_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='linkedin_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('ATM', 'ATM'), ('Credit Card', 'Credit Card'), ('PayPal', 'PayPal'), ('Crypto', 'Cryptocurrency')], default='ATM', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='expertise',
            field=models.CharField(choices=[('general_fitness', 'General Fitness'), ('yoga', 'Yoga'), ('strength_training', 'Strength Training'), ('cardio', 'Cardio'), ('nutrition', 'Nutrition'), ('pilates', 'Pilates'), ('crossfit', 'CrossFit'), ('bodybuilding', 'Bodybuilding'), ('martial_arts', 'Martial Arts')], default='general_fitness', max_length=50),
        ),
    ]
