# Generated by Django 5.1.3 on 2025-03-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_payment_currency_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, default='Add Full Name', max_length=255, null=True),
        ),
    ]
