# Generated by Django 5.1.3 on 2025-03-08 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_remove_trainer_name_remove_trainer_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='X',
            new_name='X_handle',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='twitter_handle',
        ),
    ]
