# Generated by Django 5.1.3 on 2025-03-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_alter_trainer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complete_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('question_message', models.CharField(max_length=1000)),
                ('mobile_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
