# Generated by Django 5.1.3 on 2025-03-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_appointment_alter_booking_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='available_days',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='trainer',
            name='max_bookings_per_day',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
