# Generated by Django 5.1.3 on 2025-03-10 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_trainer_available_days_trainer_max_bookings_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='Main.trainer'),
        ),
    ]
